let mapCauseFateEffect = {
    "1/1": { "name": "Thiên Vi Càn", "five_elements": "Kim - Kim", "mean": "Sáng tạo, thành công, sức mạnh, dương.", "point": "RT", "fate": "1/1", "effect": { "1": "1/5", "2": "1/3", "3": "1/2", "4": "5/1", "5": "3/1", "6": "2/1" } },
    "1/2": { "name": "Thiên Trạch Lý", "five_elements": "Kim - Kim", "mean": "Chọn lựa lối đi, cách sử nhẹ nhàng tế nhị.", "point": "T", "fate": "5/3", "effect": { "1": "1/6", "2": "1/4", "3": "1/1", "4": "5/2", "5": "3/2", "6": "2/2" } },
    "1/3": { "name": "Thiên Hỏa Đồng Nhân", "five_elements": "Kim - Hỏa", "mean": "Cộng đồng, liên kết, gắn bó, đồng tâm.", "point": "T", "fate": "1/5", "effect": { "1": "1/7", "2": "1/1", "3": "1/4", "4": "5/3", "5": "3/3", "6": "2/3" } },
    "1/4": { "name": "Thiên Lôi Vô Vọng", "five_elements": "Kim - Mộc", "mean": "Vô tư, thật thà, giản dị, ngẫu nhiên.", "point": "T", "fate": "5/7", "effect": { "1": "1/8", "2": "1/2", "3": "1/4", "4": "5/4", "5": "3/4", "6": "2/4" } },
    "1/5": { "name": "Thiên Phong Cấu", "five_elements": "Kim - Mộc", "mean": "Cám dỗ, quyến rũ, cấu kết, liên kết xấu.", "point": "X", "fate": "1/1", "effect": { "1": "1/1", "2": "1/7", "3": "1/6", "4": "5/5", "5": "3/5", "6": "2/5" } },
    "1/6": { "name": "Thiên Thủy Tụng", "five_elements": "Kim - Thủy", "mean": "Tranh chấp, nghi ngờ, bất đồng, kiện cáo.", "point": "X", "fate": "5/3", "effect": { "1": "1/2", "2": "1/8", "3": "1/5", "4": "5/6", "5": "3/6", "6": "2/6" } },
    "1/7": { "name": "Thiên Sơn Độn", "five_elements": "Kim - Thổ", "mean": "Trốn chạy, rút lui, rời chỗ cũ đến chỗ mới.", "point": "X", "fate": "1/5", "effect": { "1": "1/3", "2": "1/5", "3": "1/8", "4": "5/7", "5": "3/7", "6": "2/7" } },
    "1/8": { "name": "Thiên Địa Bỉ", "five_elements": "Kim - Thổ", "mean": "Bế tắc, đình trệ, suy thoái, tan rã, bất động.", "point": "X", "fate": "5/7", "effect": { "1": "1/4", "2": "1/6", "3": "1/7", "4": "5/8", "5": "3/8", "6": "2/8" } },

    "2/1": { "name": "Trạch Thiên Quải", "five_elements": "Kim - Kim", "mean": "Thâm nhập, quyết đoán, can đảm trừ ác.", "point": "T", "fate": "1/1", "effect": { "1": "2/5", "2": "2/3", "3": "2/2", "4": "6/1", "5": "4/1", "6": "1/1" } },
    "2/2": { "name": "Trạch Vi Đoài", "five_elements": "Kim - Kim", "mean": "Vui tươi, quang minh, niềm vui mừng.", "point": "RT", "fate": "5/3", "effect": { "1": "2/6", "2": "2/4", "3": "2/1", "4": "6/2", "5": "4/2", "6": "1/2" } },
    "2/3": { "name": "Trạch Hỏa Cách", "five_elements": "Kim - Hỏa", "mean": "Cải cách, biến đổi, cuộc cách mạng.", "point": "T", "fate": "1/5", "effect": { "1": "2/7", "2": "2/1", "3": "2/4", "4": "6/3", "5": "4/3", "6": "1/3" } },
    "2/4": { "name": "Trạch Lôi Tùy", "five_elements": "Kim - Mộc", "mean": "Kế thừa, nối tiếp, gia nhập tự nguyện.", "point": "T", "fate": "5/7", "effect": { "1": "2/8", "2": "2/2", "3": "2/3", "4": "6/4", "5": "4/4", "6": "1/4" } },
    "2/5": { "name": "Trạch Phong Đại Quá", "five_elements": "Kim - Mộc", "mean": "Trau dồi tài đức để làm việc phi thường.", "point": "T", "fate": "1/1", "effect": { "1": "2/1", "2": "2/7", "3": "2/6", "4": "6/5", "5": "4/5", "6": "1/5" } },
    "2/6": { "name": "Trạch Thủy Khốn", "five_elements": "Kim - Thủy", "mean": "Khốn cùng, khốn tận, bại hoại, nản chí.", "point": "X", "fate": "5/3", "effect": { "1": "2/2", "2": "2/8", "3": "2/5", "4": "6/6", "5": "4/6", "6": "1/6" } },
    "2/7": { "name": "Trạch Sơn Hàm", "five_elements": "Kim - Thổ", "mean": "Hòa hợp, đám cưới, hiệp định, liên minh.", "point": "T", "fate": "1/5", "effect": { "1": "2/3", "2": "2/5", "3": "2/8", "4": "6/7", "5": "4/7", "6": "1/7" } },
    "2/8": { "name": "Trạch Địa Tụy", "five_elements": "Kim - Thổ", "mean": "Tập hợp, thuận tình, đoàn thể, biểu tình.", "point": "T", "fate": "5/7", "effect": { "1": "2/4", "2": "2/6", "3": "2/7", "4": "6/8", "5": "4/8", "6": "1/8" } },

    "3/1": { "name": "Hỏa Thiên Đại Hữu", "five_elements": "Hỏa - Kim", "mean": "Có nhiều, sung túc, giàu có, nổi tiếng.", "point": "RT", "fate": "2/1", "effect": { "1": "3/5", "2": "3/3", "3": "3/2", "4": "7/1", "5": "1/1", "6": "4/1" } },
    "3/2": { "name": "Hỏa Trạch Khuê", "five_elements": "Hỏa - Kim", "mean": "Tương khắc, đối đầu, lợi dụng lẫn nhau.", "point": "X", "fate": "6/3", "effect": { "1": "3/6", "2": "3/4", "3": "3/1", "4": "7/2", "5": "1/2", "6": "4/2" } },
    "3/3": { "name": "Hỏa Vi Ly", "five_elements": "Hỏa - Hỏa", "mean": "Gắn bó, trong sáng, lý tưởng, chiếu rọi.", "point": "T", "fate": "2/5", "effect": { "1": "3/7", "2": "3/1", "3": "3/4", "4": "7/3", "5": "1/3", "6": "4/3" } },
    "3/4": { "name": "Hỏa Lôi Phê Hạp", "five_elements": "Hỏa - Mộc", "mean": "Phá hủy chướng ngại, trừng trị, tiêu diệt.", "point": "T", "fate": "6/7", "effect": { "1": "3/8", "2": "3/2", "3": "3/3", "4": "7/4", "5": "1/4", "6": "4/4" } },
    "3/5": { "name": "Hỏa Phong Đỉnh", "five_elements": "Hỏa - Mộc", "mean": "Hun đúc, rèn luyện, cải thiện, tu dưỡng.", "point": "T", "fate": "2/1", "effect": { "1": "3/1", "2": "3/7", "3": "3/6", "4": "7/5", "5": "1/5", "6": "4/5" } },
    "3/6": { "name": "Hỏa Thủy Vị Tế", "five_elements": "Hỏa - Thủy", "mean": "Việc chưa hoàn thành, rối loạn, hổn độn.", "point": "X", "fate": "6/3", "effect": { "1": "3/2", "2": "3/8", "3": "3/5", "4": "7/6", "5": "1/6", "6": "4/6" } },
    "3/7": { "name": "Hỏa Sơn Lữ", "five_elements": "Hỏa - Thổ", "mean": "Lữ khách,tạm trú, không bền vững.", "point": "X", "fate": "2/5", "effect": { "1": "3/3", "2": "3/5", "3": "3/8", "4": "7/7", "5": "1/7", "6": "4/7" } },
    "3/8": { "name": "Hỏa Địa Tấn", "five_elements": "Hỏa - Thổ", "mean": "Tiến bộ, thăng chức, thành đạt rạng rỡ.", "point": "RT", "fate": "6/7", "effect": { "1": "3/4", "2": "3/6", "3": "3/7", "4": "7/8", "5": "1/8", "6": "4/8" } },

    "4/1": { "name": "Lôi Thiên Đại Tráng", "five_elements": "Mộc - Kim", "mean": "Quyền lực lớn mạnh, tài năng, năng lực.", "point": "RT", "fate": "2/1", "effect": { "1": "4/5", "2": "4/3", "3": "4/2", "4": "8/1", "5": "2/1", "6": "3/1" } },
    "4/2": { "name": "Lôi Trạch Quy Muội", "five_elements": "Mộc - Kim", "mean": "Cô dâu, cuộc hôn nhân, công việc không bền.", "point": "X", "fate": "6/3", "effect": { "1": "4/6", "2": "4/4", "3": "4/1", "4": "8/2", "5": "2/2", "6": "3/2" } },
    "4/3": { "name": "Lôi Hỏa Phong", "five_elements": "Mộc - Hỏa", "mean": "Trù phú, thành công, trưởng thành.", "point": "RT", "fate": "2/5", "effect": { "1": "4/7", "2": "4/1", "3": "4/4", "4": "8/3", "5": "2/3", "6": "3/3" } },
    "4/4": { "name": "Lôi Vi Chấn", "five_elements": "Mộc - Mộc", "mean": "Sấm sét, chuyển động, bản năng sinh tồn.", "point": "T", "fate": "6/7", "effect": { "1": "4/8", "2": "4/2", "3": "4/3", "4": "8/4", "5": "2/4", "6": "3/4" } },
    "4/5": { "name": "Lôi Phong Hằng", "five_elements": "Mộc - Mộc", "mean": "Trường cửu, kiên tâm, lòng trung thành.", "point": "T", "fate": "2/1", "effect": { "1": "4/1", "2": "4/7", "3": "4/6", "4": "8/5", "5": "2/5", "6": "3/5" } },
    "4/6": { "name": "Lôi Thủy Giải", "five_elements": "Mộc - Thủy", "mean": "Giải phóng, chấm dứt khó khăn, ân xá.", "point": "T", "fate": "6/3", "effect": { "1": "4/2", "2": "4/8", "3": "4/5", "4": "8/6", "5": "2/6", "6": "3/6" } },
    "4/7": { "name": "Lôi Sơn Tiểu Quả", "five_elements": "Mộc - Thổ", "mean": "Ưu thế của kẻ yếu, giới hạn, tin tức nhỏ.", "point": "X", "fate": "2/5", "effect": { "1": "4/3", "2": "4/5", "3": "4/8", "4": "8/7", "5": "2/7", "6": "3/7" } },
    "4/8": { "name": "Lôi Địa Dự", "five_elements": "Mộc - Thổ", "mean": "Hân hoan, chiến thắng, nhiệt tâm.", "point": "RT", "fate": "6/7", "effect": { "1": "4/4", "2": "4/6", "3": "4/7", "4": "8/8", "5": "2/8", "6": "3/8" } },

    "5/1": { "name": "Phong Thiên Tiểu Súc", "five_elements": "Mộc - Kim", "mean": "Ngăn Trở nhỏ, ngưng trệ, kìm hãm.", "point": "X", "fate": "3/2", "effect": { "1": "5/5", "2": "5/3", "3": "5/2", "4": "1/1", "5": "7/1", "6": "6/1" } },
    "5/2": { "name": "Phong Trạch Trung Phu", "five_elements": "Mộc - Kim", "mean": "Có đức tin, trung thực, uy tín, thành thật.", "point": "T", "fate": "7/4", "effect": { "1": "5/6", "2": "5/4", "3": "5/1", "4": "1/2", "5": "7/2", "6": "6/2" } },
    "5/3": { "name": "Phong Hỏa Gia Nhân", "five_elements": "Mộc - Hỏa", "mean": "Gia đình, quần thể xã hội tập hợp lại.", "point": "T", "fate": "3/6", "effect": { "1": "5/7", "2": "5/1", "3": "5/4", "4": "1/3", "5": "7/3", "6": "6/3" } },
    "5/4": { "name": "Phong Lôi Ích", "five_elements": "Mộc - Mộc", "mean": "Tăng trưởng, vượt lên, phát triển thêm.", "point": "RT", "fate": "7/8", "effect": { "1": "5/8", "2": "5/2", "3": "5/3", "4": "1/4", "5": "7/4", "6": "6/4" } },
    "5/5": { "name": "Phong Vi Tốn", "five_elements": "Mộc - Mộc", "mean": "Dịu dàng, uyển chuyển khéo léo, tế nhị.", "point": "T", "fate": "3/2", "effect": { "1": "5/1", "2": "5/7", "3": "5/6", "4": "1/5", "5": "7/5", "6": "6/5" } },
    "5/6": { "name": "Phong Thủy Hoán", "five_elements": "Mộc - Thủy", "mean": "Ly tán, giải thể, trốn đi xa, gián đoạn.", "point": "X", "fate": "7/4", "effect": { "1": "5/2", "2": "5/8", "3": "5/5", "4": "1/6", "5": "7/6", "6": "6/6" } },
    "5/7": { "name": "Phong Sơn Tiệm", "five_elements": "Mộc - Thổ", "mean": "Tiến dần dần, tiến bộ, thăng chức.", "point": "RT", "fate": "3/6", "effect": { "1": "5/3", "2": "5/5", "3": "5/8", "4": "1/7", "5": "7/7", "6": "6/7" } },
    "5/8": { "name": "Phong Địa Quan", "five_elements": "Mộc - Thổ", "mean": "Suy tư, quan sát, thấy xa, khả năng tiên tri.", "point": "T", "fate": "7/8", "effect": { "1": "5/4", "2": "5/6", "3": "5/7", "4": "1/8", "5": "7/8", "6": "6/8" } },

    "6/1": { "name": "Thủy Thiên Nhu", "five_elements": "Thủy - Kim", "mean": "Chờ đợi, nhẫn nại, sự kiên nhẫn dẻo dai.", "point": "T", "fate": "3/2", "effect": { "1": "6/5", "2": "6/3", "3": "6/3", "4": "2/1", "5": "8/1", "6": "5/1" } },
    "6/2": { "name": "Thủy Trạch Tiết", "five_elements": "Thủy - Kim", "mean": "Phân giới, giới hạn, các luật lệ, kiềm chế.", "point": "X", "fate": "7/4", "effect": { "1": "6/6", "2": "6/4", "3": "6/1", "4": "2/2", "5": "8/2", "6": "5/2" } },
    "6/3": { "name": "Thủy Hỏa Ký Tế", "five_elements": "Thủy - Hỏa", "mean": "Việc đã thành, trật tự văn hồi, thành công.", "point": "RT", "fate": "3/6", "effect": { "1": "6/7", "2": "6/1", "3": "6/4", "4": "2/3", "5": "8/3", "6": "5/3" } },
    "6/4": { "name": "Thủy Lôi Truân", "five_elements": "Thủy - Mộc", "mean": "Gian lao, khó khăn ban đầu, nguy hiểm.", "point": "X", "fate": "7/8", "effect": { "1": "6/8", "2": "6/2", "3": "6/3", "4": "2/4", "5": "8/4", "6": "5/4" } },
    "6/5": { "name": "Thủy Phong Tỉnh", "five_elements": "Thủy - Mộc", "mean": "Che dấu, huyền bí, kiên nhẫn, trầm lặng.", "point": "T", "fate": "3/2", "effect": { "1": "6/1", "2": "6/7", "3": "6/6", "4": "2/5", "5": "8/5", "6": "5/5" } },
    "6/6": { "name": "Thủy Vi Khảm", "five_elements": "Thủy - Thủy", "mean": "Nguy hiểm, bí mật, ăn trộm, vực thẳm.", "point": "X", "fate": "7/4", "effect": { "1": "6/2", "2": "6/8", "3": "6/5", "4": "2/6", "5": "8/6", "6": "5/6" } },
    "6/7": { "name": "Thủy Sơn Kiển", "five_elements": "Thủy - Thổ", "mean": "Chướng ngại, trắc trở, bế tắc, nguy khốn.", "point": "X", "fate": "3/6", "effect": { "1": "6/3", "2": "6/5", "3": "6/8", "4": "2/7", "5": "8/7", "6": "5/7" } },
    "6/8": { "name": "Thủy Địa Tỷ", "five_elements": "Thủy - Thổ", "mean": "Tương trợ, hòa thuận, tập hợp, thống nhất.", "point": "T", "fate": "7/8", "effect": { "1": "6/4", "2": "6/6", "3": "6/7", "4": "2/8", "5": "8/8", "6": "5/8" } },

    "7/1": { "name": "Sơn Thiên Đại Súc", "five_elements": "Thổ - Kim", "mean": "Tích lũy tài năng, phát triển cá nhân.", "point": "RT", "fate": "4/2", "effect": { "1": "7/5", "2": "7/3", "3": "7/2", "4": "3/1", "5": "5/1", "6": "8/1" } },
    "7/2": { "name": "Sơn Trạch Tổn", "five_elements": "Thổ - Kim", "mean": "Thua thiệt, tổn hại, rút lui, suy thoái.", "point": "X", "fate": "8/4", "effect": { "1": "7/6", "2": "7/4", "3": "7/1", "4": "3/2", "5": "5/2", "6": "8/2" } },
    "7/3": { "name": "Sơn Hỏa Bí", "five_elements": "Thổ - Hỏa", "mean": "Sắc đẹp, xinh xắn, hình thức, nghệ thuật.", "point": "X", "fate": "4/6", "effect": { "1": "7/7", "2": "7/1", "3": "7/4", "4": "3/3", "5": "5/3", "6": "8/3" } },
    "7/4": { "name": "Sơn Lôi Di", "five_elements": "Thổ - Mộc", "mean": "Thức phẩm, cái miệng, tư cách, sự nói.", "point": "T", "fate": "8/8", "effect": { "1": "7/8", "2": "7/2", "3": "7/5", "4": "3/4", "5": "5/4", "6": "8/4" } },
    "7/5": { "name": "Sơn Phong Cổ", "five_elements": "Thổ - Mộc", "mean": "Sửa sai, cải tiến, suy tính, lo toan.", "point": "X", "fate": "4/2", "effect": { "1": "7/1", "2": "7/7", "3": "7/6", "4": "3/5", "5": "5/5", "6": "8/5" } },
    "7/6": { "name": "Sơn Thủy Mông", "five_elements": "Thổ - Thủy", "mean": "Điên cuồng tuổi trẻ, mù quáng, liều lĩnh.", "point": "X", "fate": "8/4", "effect": { "1": "7/2", "2": "7/8", "3": "7/5", "4": "3/6", "5": "5/6", "6": "8/6" } },
    "7/7": { "name": "Sơn Vi Cấn", "five_elements": "Thổ - Thổ", "mean": "Ngừng nghĩ, bất động, ngưng trệ, im lặng.", "point": "X", "fate": "4/6", "effect": { "1": "7/3", "2": "7/5", "3": "7/8", "4": "3/7", "5": "5/7", "6": "8/7" } },
    "7/8": { "name": "Sơn Địa Bác", "five_elements": "Thổ - Thổ", "mean": "Bùng nổ, sụp đổ, suy thoái, phá sản.", "point": "X", "fate": "8/8", "effect": { "1": "7/4", "2": "7/6", "3": "7/7", "4": "3/8", "5": "5/8", "6": "8/8" } },

    "8/1": { "name": "Địa Thiên Thái", "five_elements": "Thổ - Kim", "mean": "Thái bình, phồn vinh, hòa hợp cân bằng.", "point": "T", "fate": "4/2", "effect": { "1": "8/5", "2": "8/3", "3": "8/2", "4": "4/1", "5": "6/1", "6": "7/1" } },
    "8/2": { "name": "Địa Trạch Lâm", "five_elements": "Thổ - Kim", "mean": "Trưởng thành từng bước, thành công lớn.", "point": "RT", "fate": "8/4", "effect": { "1": "8/6", "2": "8/4", "3": "8/1", "4": "4/2", "5": "6/2", "6": "7/2" } },
    "8/3": { "name": "Địa Hỏa Minh Di", "five_elements": "Thổ - Hỏa", "mean": "Ánh sánh bị che lấp, buồn thảm, đau lòng.", "point": "X", "fate": "4/6", "effect": { "1": "8/7", "2": "8/1", "3": "8/4", "4": "4/3", "5": "6/3", "6": "7/3" } },
    "8/4": { "name": "Địa Lôi Phục", "five_elements": "Thổ - Mộc", "mean": "Trở về, sự đổi mới, chấm dứt đen tối.", "point": "T", "fate": "8/8", "effect": { "1": "8/8", "2": "8/2", "3": "8/3", "4": "4/4", "5": "6/4", "6": "7/4" } },
    "8/5": { "name": "Địa Phong Thăng", "five_elements": "Thổ - Mộc", "mean": "Thăng tiến, thăng chức, tích lũy tài sản.", "point": "RT", "fate": "4/2", "effect": { "1": "8/1", "2": "8/7", "3": "8/6", "4": "4/5", "5": "6/5", "6": "7/5" } },
    "8/6": { "name": "Địa Thủy Sư", "five_elements": "Thổ - Thủy", "mean": "Quân đội, chỉ huy, bạo loạn, đau khổ.", "point": "X", "fate": "8/4", "effect": { "1": "8/2", "2": "8/8", "3": "8/5", "4": "4/6", "5": "6/6", "6": "7/6" } },
    "8/7": { "name": "Địa Sơn Khiêm", "five_elements": "Thổ - Thổ", "mean": "Khiêm nhường, mềm mỏng, giản dị.", "point": "T", "fate": "4/6", "effect": { "1": "8/3", "2": "8/5", "3": "8/8", "4": "4/7", "5": "6/7", "6": "7/7" } },
    "8/8": { "name": "Địa Vi Khôn", "five_elements": "Thổ - Thổ", "mean": "Thụ động, mềm mỏng, ngoại giao, âm.", "point": "T", "fate": "8/8", "effect": { "1": "8/4", "2": "8/6", "3": "8/7", "4": "4/8", "5": "6/8", "6": "7/8" } },
}

module.exports = {
    mapCauseFateEffect
};
