let mapHexagramType = {
    "1/1": "bg-danger",
    "1/2": "bg-primary",
    "1/3": "bg-primary",
    "1/4": "bg-primary",
    "1/5": "bg-secondary",
    "1/6": "bg-secondary",
    "1/7": "bg-secondary",
    "1/8": "bg-secondary",

    "2/1": "bg-primary",
    "2/2": "bg-danger",
    "2/3": "bg-primary",
    "2/4": "bg-primary",
    "2/5": "bg-primary",
    "2/6": "bg-secondary",
    "2/7": "bg-primary",
    "2/8": "bg-primary",

    "3/1": "bg-danger",
    "3/2": "bg-secondary",
    "3/3": "bg-primary",
    "3/4": "bg-primary",
    "3/5": "bg-primary",
    "3/6": "bg-secondary",
    "3/7": "bg-secondary",
    "3/8": "bg-danger",

    "4/1": "bg-danger",
    "4/2": "bg-secondary",
    "4/3": "bg-danger",
    "4/4": "bg-primary",
    "4/5": "bg-primary",
    "4/6": "bg-primary",
    "4/7": "bg-secondary",
    "4/8": "bg-danger",

    "5/1": "bg-secondary",
    "5/2": "bg-primary",
    "5/3": "bg-primary",
    "5/4": "bg-danger",
    "5/5": "bg-primary",
    "5/6": "bg-secondary",
    "5/7": "bg-danger",
    "5/8": "bg-primary",

    "6/1": "bg-primary",
    "6/2": "bg-secondary",
    "6/3": "bg-danger",
    "6/4": "bg-secondary",
    "6/5": "bg-primary",
    "6/6": "bg-secondary",
    "6/7": "bg-secondary",
    "6/8": "bg-primary",

    "7/1": "bg-danger",
    "7/2": "bg-secondary",
    "7/3": "bg-secondary",
    "7/4": "bg-primary",
    "7/5": "bg-secondary",
    "7/6": "bg-secondary",
    "7/7": "bg-secondary",
    "7/8": "bg-secondary",

    "8/1": "bg-primary",
    "8/2": "bg-danger",
    "8/3": "bg-secondary",
    "8/4": "bg-primary",
    "8/5": "bg-danger",
    "8/6": "bg-secondary",
    "8/7": "bg-primary",
    "8/8": "bg-primary",
}

  
module.exports = {
    mapHexagramType,
};
